Use MODELOPARCIAL2_PUNTO2

--A
SELECT P.NOMBRE,MAX(PC.PESO) AS PESO,E.ESPECIE FROM PARTICIPANTES AS P
INNER JOIN PESCA AS PC ON P.IDPARTICIPANTE=PC.IDPARTICIPANTE
INNER JOIN ESPECIES AS E ON PC.IDESPECIE = E.IDESPECIE
GROUP BY P.NOMBRE,E.ESPECIE

--B
select DISTINCT E.ESPECIE,PC.NOMBRE,PC.APELLIDO from ESPECIES AS E
inner join pesca as P on E.IDESPECIE = P.IDESPECIE
inner join PARTICIPANTES as PC ON P.IDPARTICIPANTE=pc.IDPARTICIPANTE
where E.ESPECIE NOT LIKE '%bagre%' 

--C
SELECT P.NOMBRE,AVG(PC.PESO) AS PROM_PESO,E.ESPECIE FROM PARTICIPANTES AS P
INNER JOIN PESCA AS PC ON P.IDPARTICIPANTE=PC.IDPARTICIPANTE
INNER JOIN ESPECIES AS E ON PC.IDESPECIE = E.IDESPECIE
GROUP BY P.NOMBRE,E.ESPECIE
having (AVG(PC.PESO))<=30

--D
SELECT 
(select count(*) from PESCA WHERE DATEPART(HOUR,FECHA_HORA) < 21 AND DATEPART(HOUR,FECHA_HORA) <6 AND IDESPECIE=E.IDESPECIE) AS PESCA,
ESPECIE
FROM ESPECIES AS E

--E
DESCARTADOS
SELECT APELLIDO,NOMBRE,
(SELECT COUNT(*) FROM PESCA WHERE IDESPECIE IS NULL AND IDPARTICIPANTE=P.IDPARTICIPANTE) AS Descartados,
(SELECT COUNT(*) FROM PESCA WHERE IDESPECIE IS NOT NULL AND IDPARTICIPANTE=P.IDPARTICIPANTE) AS No_Descartados
FROM PARTICIPANTES AS P

--F
SELECT ISNULL(PT.NOMBRE,''),ISNULL(PT.APELLIDO,''),E.ESPECIE FROM ESPECIES AS E
LEFT JOIN PESCA AS P on E.IDESPECIE = P.IDESPECIE
LEFT JOIN PARTICIPANTES AS PT on P.IDPARTICIPANTE = PT.IDPARTICIPANTE



